server.port=8888
spring.application.name=config-service
spring.cloud.config.server.git.uri=git@github.com:Alexandr-cloud/user-service-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.ignore-local-ssh-settings=false