server.port=8888
spring.application.name=config-service
spring.cloud.config.server.git.uri=https://Alexandr-cloud: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@github.com/Alexandr-cloud/user-service-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true